disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Shivan Malde | DevOps Manager and Platform Engineer"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "DevOps Manager and Platform Engineer specializing in Kubernetes, Infrastructure as Code, and Enterprise-scale CI/CD"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Shivan Malde"
  image = "/img/pro_portrait.jpg"
  imageQuality = 96
  bio = "London-based DevOps manager and platform engineer with a proven track record of delivering scalable and reliable infrastructure solutions. Specialised in Kubernetes, Infrastructure as Code, and enterprise-scale CI/CD."
  links = [
    { github = "https://github.com/ShivanMalde" },
    { linkedin = "https://linkedin.com/in/shivanmalde/" },
  ]
