# -- Main Menu --

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Services"
  pageRef = "services"
  weight = 20

[[main]]
  name = "Intake"
  pageRef = "intake"
  weight = 25

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/ShivanMalde"
  weight = 100

  [[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://linkedin.com/in/shivanmalde"
  weight = 200